# Use postgres/example user/password credentials
version: '3'

services:
  db:
    build: ./db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: mmo
      POSTGRES_PASSWORD: mmoChallenge
      POSTGRES_DB: welcome_mmo
  app:
    build: ./app
    ports: 
      - "3000:3000" 
    depends_on: 
      - db
    restart: on-failure
