# Use postgres/example user/password credentials
version: '3'

services:
  db:
    build: ./db
    environment:
      IMMO_DB_HOST: db
      IMMO_DB_USER: mmo
      IMMO_DB_PASSWORD: mmoChallenge
      IMMO_DB: welcome_mmo
  app:
    build: ./app
    ports: 
      - "3000:3000" 
    depends_on: 
      - db
    restart: on-failure
