# Use postgres/example user/password credentials
version: '3.1'

services:
  app:
    build: ./app
    ports: 
        - "3000:3000"
    depends_on: 
        - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - MMO_DB_HOST= db
      - MMO_DB_USER= mmo
      - MMO_DB_PASSWORD= mmoChallenge
      - MMO_DB= welcome_mmo
    volumes:
        - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
        - 5432:5432  